excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://Damagarawa.github.io
name: DANDALIN DAMAGARAWA
description: Fasahar sadarwar zamani
author: Engr Abdoulkadir Prero
avatar: http://www.gravatar.com/avatar/d41d8cd98f00b204e9800998ecf8427e?s=120&d=mm&r=g
ga_domain: zinderniger
ga_tracking_id: damagaram